version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev

  redis:
    container_name: redis
    image: redis:alpine

  celery:
    container_name: celery
    restart: always
    build:
      context: ./server
    command: celery -A server worker -l info
    volumes:
      - ./server:/server
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - server

  celery-beat:
    restart: always
    build:
      context: ./server
    command: celery -A server beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./server:/server
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - server

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
